# Generated by Django 6.0.7 on 2026-07-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name="ID в Телеграм"),
        ),
    ]
