# Generated by Django 6.0.7 on 2026-07-30 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.TextField(help_text="Что конкретно нужно сделать?", verbose_name="Действие")),
                ("location", models.CharField(blank=True, max_length=255, verbose_name="Место")),
                ("time", models.CharField(blank=True, max_length=100, verbose_name="Время")),
                (
                    "estimated_duration_seconds",
                    models.PositiveSmallIntegerField(
                        default=120, help_text="Максимум 120 секунд.", verbose_name="Время на выполнение (секунды)"
                    ),
                ),
                (
                    "periodicity_days",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Через сколько дней повторять напоминание. От 1 до 7.",
                        verbose_name="Периодичность (в днях)",
                    ),
                ),
                ("reward_description", models.TextField(blank=True, verbose_name="Вознаграждение (текстом)")),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, если это приятная привычка-награда.",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="Опубликовать в общий доступ")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "pleasant_habit",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_pleasant": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rewarded_for",
                        to="habits.habit",
                        verbose_name="Приятная привычка-награда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["-created_at"],
            },
        ),
    ]
